name: student_chat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutx:
    path: ../flutx
  flutter_svg: ^2.0.7
  aad_oauth: "^0.4.4"
  graphql: ^5.2.0-beta.4
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.0.0
  intl: ^0.17.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  gql_build: ^0.8.0
  build_runner: ^2.0.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/